### PR TITLE
Boundary integrals

### PR DESCRIPTION
**Pull request by lmoresi**
Tracking down the issues with the natural boundary terms.
See examples provided in file `Jupyterbook/Notebooks/WIP/SurfaceIntegralTerms.py`

All fine when bc/s are linear as there are no additional contributions to the system Jacobian.

Problems arise when the boundary condition is non-linear (we are just testing the case where the boundary condition depends on the solution velocity but not on gradients or pressures). 

The body-term Jacobian (J) and the Jacobean Preconditioner (JP) differ because of the (1,1) block — zero in J, non-zero in the JP matrix. When we add the `BdJacobian` and `BdJacobianPreconditioner` functions, it is clear that these are not being loaded up correctly:

 1) There are no changes to the system Jacobian (extracted from the SNES object)
 2) There is a change to the Jacobian Preconditioner term (extracted from the SNES object)
 3) The functions that are called are those from the Jacobian, not from the Jacobian-preconditioner (though they should be the same in most cases).
 4) Even though only J is called, the resulting changes end up in the JP ... 
 5) We are using the `PetscWeakFormSetIndexBdJacobian` and `PetscWeakFormSetIndexBdJacobianPreconditioner` calls but there are no examples of the latter that I can find.  

**Not sure if this is a setup bug or something that is going wrong in SNES, @knepley, can you take a look ? I have looked through the examples to find the strategy for calling these functions but they are absent ...

### CODE REVIEW

**Comment by lmoresi** [comment]
To run this branch, there is a modified fork of PETSc here: https://gitlab.com/lmoresi/petsc. This swaps out the Jacobian preconditioner matrix for the surface integrals for the Jacobian itself. This works for these particular examples and does not collide with the Stokes use of additional terms in the Jacobian preconditioner. 

Examples: 

  - Jupyterbook/Notebooks/Examples-Utilities/SurfaceIntegralTerms.py
  - Jupyterbook/Notebooks/Examples-Convection/Ex_Convection_Cylinder-FS.py
  - Jupyterbook/Notebooks/Examples-StokesFlow/Ex_Stokes_Disk_CylCoords.py
  - Jupyterbook/Notebooks/Examples-Convection/Ex_Convection_Disc_InternalHeat.py
  - Jupyterbook/Notebooks/Examples-StokesFlow/Ex_Stokes_Cartesian_SolC.py

That final example is just to show that we can get SolCx to work with the alternate formulation for the bc's.


That's all for now. 

@knepley for a comment on the petsc issue.

**Comment by lmoresi** [comment]
Added / updated the uw symbolic machinery for surface normals so we can access the petsc_n variable in the point-wise functions. This now works so we can set a no-normal-flow boundary condition like this:

Screenshot 2024-01-07 at 2 06 53 pm


```
Gamma = elliptical_mesh.Gamma

stokes.add_natural_bc(10000 * Gamma.dot(v_soln.sym) *  Gamma, "Outer")
stokes.add_natural_bc(10000 * Gamma.dot(v_soln.sym) *  Gamma, "Inner")
```

The spherical tests, cylindrical models and the convection in a disc example work with this or analytic normals. Convergence is very rapid now that the Jacobians are properly defined (still buggy in PESTc as far as I can see ... @knepley ?). 

Would be good to compare this to the rotated stiffness matrix approach.

L

PS - couple of tests not passing. One is due to the JIT changes, another due to the interpolation issue raised separately.

**Comment by julesghub** [comment]
I see some failing test. These need fixing before we can put this into `development`.

```
FAILED tests/test_0004_pointwise_fns.py::test_build_functions - AttributeError: 'BaseScalar' object has no attribute '_ccodestr'
FAILED tests/test_0004_pointwise_fns.py::test_build_boundary_functions - AttributeError: 'BaseScalar' object has no attribute '_ccodestr'
FAILED tests/test_0004_pointwise_fns.py::test_debug_pointwise_functions - AttributeError: 'BaseScalar' object has no attribute '_ccodestr'
```

**Comment by lmoresi** [comment]
@julesghub - I thought I'd fixed those ... turns out I did (pytest tests/*pointwise*py is fine. But not if I collect all the tests first. Strange. I'll take a quick look.

**Comment by lmoresi** [comment]
I have a quasi-fix for the broken point wise function tests which occurs due to an interaction between multiple tests (test pass individually but not in combination). 

The simplest combination of breaking tests is:

```bash
 pytest tests/test_0004_pointwise_fns.py tests/test_0601_mesh_vector_calc.py
```


I fix this by adding code-patch functions for basis vectors and surface normals to the `mesh` object at build time, NOT at the JIT compile time. I think this is because there are multiple meshes being built and we may not be correctly isolating the caching of compiled objects. It's also the case that the vector tests are not compiling any functions / do not access the JIT environment / contains no solves so something is assumed to be built even though the JIT path is not visited. 

This needs more investigation because we don't do this combination very often but we will have multiple meshes when we do things like adaptive refinement. It's also not appropriate to have code-printing / compiler options in the meshing system. I'd prefer these to be clean.

However, in part this is due to the way the sympy code printing works - adding functionality to previously defined *types* themselves. Hard to keep this clean.

**Comment by lmoresi** [comment]
To fix the benchmark Darcy-flow cases, we need the prescribed pressure gradient to be part of the flux term and therefore to be described through the constitutive law. That's slightly weird so we might have to think about that. 

Fixed the anti-batman pattern for Darcy and some other inconsistencies that I found in the projection solvers. Ensured that the tests pass.

**Comment by julesghub** [comment]
> To fix the benchmark Darcy-flow cases, we need the prescribed pressure gradient to be part of the flux term and therefore to be described through the constitutive law. That's slightly weird so we might have to think about that.


Given the above are you happy if we merge this branch into `dev`?

**Comment by lmoresi** [comment]
I'd be happy to merge this in as soon as we have the appropriate docker lined up (with the breaking-fix-petsc).

**Comment by lmoresi** [comment]
Fixed up the Parsons & Daly kernel "benchmark". A quantitative version of this should go into the benchmarking stack @bknight1 ! The only thing here that is different is that we are integrating along an internal boundary and so petsc does not know about the normals (is that true @knepley ?) so I have to provide them as a sympy vector.

**Comment by knepley** [comment]
PETSc knows about normals, but they are not guaranteed to be oriented as a surface. We have the same problem in PyLith. We can do an extra orientation step beforehand to make sure that internal surface is oriented.

**Comment by lmoresi** [comment]
Tests are passing, merge to dev and continue the eternal wheel of debugging
